### ISSUE TITLE
feat(slack pipeline): read secrets from `env` or `volumeMount`

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix-docs#56]
the current slack image uses `kubectl` to read a secret with a known name to find out the channel hook to send the notification to;

a better approach would to support reading the secret from env or from a file within the local system; this would allow penny to use `env` or `volumeMounts` on her pipeline spec. This would also making reading a secret with a known name redundant, so we can remove it.

## tasks

- [ ] support for setting the slack hook url from a environment variable
- [ ] support for setting the slack hook url from the a file at a known location
- [ ] no longer read secrets from a secret with a known name
- [ ] update docs
- [ ] bump the version and release a new image
