### ISSUE TITLE
feat(snyk pipeline): read token from env

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix-docs#58]
the current sny image uses `kubectl` to read a secret with a known name to find out the token to use when running the snyk cli

a better approach would to support reading the token from env or from a file within the local system; this would allow penny to use `env` or `volumeMounts` on her pipeline spec. This would also making reading a secret with a known name redundant, so we can remove it.

## tasks

- [ ] support for getting the token from a environment variable
- [ ] support for getting the token from a volumeMount
- [ ] drop support from reading from a known secret
- [ ] update docs
- [ ] bump the version and release a new image
