### ISSUE TITLE
feat(snyk/trivy pipeline): check for images in `/kratix/output` instead of input

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix-docs#59]
both the snyk and the trivy pipeline image are looking for `image` keys in the documents they find in the `/kratix/input` directory.

this a reminiscent from the days the kratix pipelines would copy whatever was available in the previous container `output` into the next container `input`; now that this is no longer how kratix works, this behaviour no longer makes much sense;

## Tasks

- [x] snyk pipeline image checks `/kratix/output` instead of `/kratix/input`
- [x] trivy pipeline image checks `/kratix/output` instead of `/kratix/input`
- [x] new snyk image available with a new version
- [x] new trivy image available with a new version
