### ISSUE TITLE
docs: Operator troubleshooting/FAQ page

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#67]
As **a platform engineer using Kratix** 
I want an **operators' troubleshooting page** 
So that **I can quickly see common reasons & fixes for why my deployment of Kratix isn't working**

----
This story is about adding an initial Troubleshooting page for people trying to deploy and maintain Kratix. It should include useful links for people trying to do common tasks in Kratix.

---
**Tasks**
- [ ] Brainstorm common operator tasks in Kratix
- [ ] Write docs with answers
- [ ] Get feedback on answers from Principals/Chris

**Comment by aclevername** [comment]
@SaphMB ready for review!
