### ISSUE TITLE
Define approach/pattern for quickstart guides and docs

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#71]
We want to create quick-start videos and docs showing how people can use Kratix in common cloud providers. We may want to scale this out as we hear about different types of clouds being used, so we should have a consistent pattern for this content.

**Context: https://www.notion.so/syntasso/Quick-starts-for-Cloud-c29fe365fff644ad9eeb11eedd91aa64?pvs=4**
Key purpose of these videos from doc:
- Customers can follow along and deploy Kratix in the major cloud providers
  - Fewer customers ask us how to deploy Kratix to the cloud
- CA have more resources they can share with prospects to get started with Kratix

## Tasks
- [x] Define docs template structure
- [x] Define core steps for the videos
-  e.g. Quick intro to Kratix, pre-requisites in your cloud, installing kratix, installing a promise, requesting a resource
- [x] Define the look and feel of any cards/slides in the video (chat to @danielbryantuk about this one and the one above)

**Comment by aclevername** [comment]
# Docs

## Prior art
Today our [quick-start guide](https://docs.kratix.io/main/quick-start) for kratix is:

1. Install cert-manager
1. Install Kratix and Flux
    - this includes minio, because its designed to be single cluster all in-one
1. Install configure Kratix and Flux (destinations, statestore, kustomizations)
1. Install a promise to test it works

Our [full installation guide](https://docs.kratix.io/main/guides/installing-kratix) for multi-cluster is:
1. Create platform cluster if doesn't exist, no guidance on how apart from KinD
1. Install cert-manager
1. Install Kratix
1. Setup statestore, 3 options:
    - minio in cluster (only works on KinD, not useful)
    - gitea in cluster (only works on KinD, not useful)
    - Custom where we link to our generic docs on configuring kratix with the details of a git repo/bucket. we leave it up to them to create it
1. Create worker cluster if it doesn't exist, no guidance on how apart from KinD
1. Install Flux on worker
1. Configure flux to read from statestore
1. Register worker as destination
1. Check canary namespace exists as health check

Of all of these, none of them are cloud provider specific unless we want to:
- recommend they use the cloud providers available statestore
   - GCP- GCS Bucket (GCP has no self-hosted git provider, they [deprecated](https://cloud.google.com/source-repositories/docs) it lol)
   - AWS- S3 Bucket or CodeCommit
   - Azure- Azure Devops Repo ([Azure buckets isn't a thing](https://www.google.com/search?q=azure+s3-compatible&oq=azure+s3-compatible&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIICAEQABgWGB4yDQgCEAAYhgMYgAQYigUyDQgDEAAYhgMYgAQYigUyDQgEEAAYhgMYgAQYigUyCggFEAAYgAQYogQyCggGEAAYgAQYogTSAQgxODU4ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8))
- Document how to create a cluster for the cloud provider
    - terrible idea

## Docs Proposal
We improve our existing multi cluster documentation to remove the KinD bias, make cloud appear first-class (even if not that much changes between them) and add cloud-specific section in places like this: 
![output](https://github.com/syntasso/kratix-docs/assets/19669095/61d9bc94-a1e5-4326-b114-b57b234cff8e)

We have this under 
- Setup state store
- Configure flux
- Register destination

For the above we can add both:
- links to using the cloud-specific tools/solutions for the above. E.g. for aws:
   - links to creating s3 bucket/cloudcommit repo
   - how to let Kratix authenticate with the bucket/cloudcommit repo,  pointing at our existing docs and maybe showing an example
   - how to let flux authenticate with bucket/cloudcommit repo, pointing to existing flux docs
- a general recommendation as well that isn't cloud specific- e.g setup a github repo (using github/gitlab/your compaies git provider is going to be way more popular than any cloud provided statestore)

**Comment by aclevername** [comment]
# Video

## Prior art
We don't have anything like this atm

## Proposal
As documented in comment before, there isn't really anything cloud provider specific with the exception of using a statestore provided by the cloud. For the sake of this video being a more compelling usecae of kratix I think it makes sense to use Github and not the cloud provider. We could not do this and intead show the creation of an azure devops repo/s3 bucket/gcs bucket, but that just isn't good and to anybody with any gitops knowledge will find it weird.

I think the videos should all be the same, with the exception of:
1. Video starts showing the cloud provider console, show the clusters (platform and worker) exists in console
1. Show a brief look at the cloud provider docs used to create it, e.g. show them [this page](https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html) for a couple of second and link to it in the video
1. Setup terminal to make it clear we are using a cloud provider cluster, e.g. 
![Screenshot 2024-06-28 at 15 41 38](https://github.com/syntasso/kratix-docs/assets/19669095/7415ad9e-cc56-49f3-a2dd-a8310b953351)

Thats it. The rest is following along with our existing documentation for installing/configuring kratix and flux.

**Comment by aclevername** [comment]
Pending the chat with @danielbryantuk until Monday

**Comment by aclevername** [comment]
skipping story boarding for now, we might come back to it later
