### ISSUE TITLE
Create quick start video & docs for GCP

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#72]
As **Penny** 
I want **a short (10 minute) videos & docs on deploying SKE to GCP** 
so that **I know how to deploy Kratix in my GCP environment**

---

**Tasks**
- [ ] Record & edit short video
- [ ] Write docs
- [x] Make any^ template code available (promise, resource request etc.)
- [ ] Let CA know **_new content_** is available

^There may not be code

**Comment by kirederik** [comment]
pending feedback on video

**Comment by aclevername** [comment]
https://syntasso.slack.com/archives/C044T9ZFUMN/p1720518490302219?thread_ts=1720092285.864229&cid=C044T9ZFUMN

**Comment by abangser** [comment]
Template code is now available in https://github.com/syntasso/kratix-examples/tree/main/quickstart-install-gcp-gke

**Comment by aclevername** [comment]
Video public https://www.youtube.com/watch?v=Zkh3FIGMsds

closing
