### ISSUE TITLE
Create quick start docs and video for AWS

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#73]
As **Penny** 
I want **a short (10 minute) videos & docs on deploying SKE to AWS** 
so that **I know how to deploy Kratix in my GCP environment**

---

**Tasks**
- [ ] Record & edit short video
- [ ] Write docs
- [ ] Make any^ template code available (promise, resource request etc.)
- [ ] Let CA know **_new content_** is available

^There may not be code

**Comment by aclevername** [comment]
Lets finish #72 first before working on this

**Comment by abangser** [comment]
Spoke with Jake. I am going to tackle docs here first, then in #74, then look at what making code templates available may look like (for this, GCP and Azure) and hold off on video til we get answers in #72 .

**Comment by abangser** [comment]
Updated docs here: https://github.com/syntasso/kratix-docs/pull/82

Slightly worried about fargate causing problems, but decided to not spend time there. If we see that as an issue we may want to provide extended directions there. The only reason I am curious about this is because the AWS docs default to pushing you there (https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html)

**Comment by abangser** [comment]
An example of sharing the code is being discussed here: https://syntasso.slack.com/archives/C044T9ZFUMN/p1720520188495129

**Comment by ChunyiLyu** [comment]
Video: https://www.youtube.com/watch?v=PSm_C4-dIvM
Example: https://github.com/syntasso/kratix-examples/tree/main/quickstart-install-aws-eks
