### ISSUE TITLE
Create quick start video & docs for Azure

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#74]
As **Penny** 
I want **a short (10 minute) videos & docs on deploying SKE to Azure** 
so that **I know how to deploy Kratix in my Azure environment**

---

**Tasks**
- [ ] Record & edit short video
- [ ] Write docs
- [ ] Make any^ template code available (promise, resource request etc.)
- [ ] Let CA know **_new content_** is available

^There may not be code

**Comment by aclevername** [comment]
Lets finish #72 first before working on this

**Comment by aclevername** [comment]
https://youtu.be/pj_AEaPdJjg

https://github.com/syntasso/kratix-examples/tree/main/quickstart-install-azure-aks
