### ISSUE TITLE
[docs] document how to use the CLI in docs.kratix.io

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#86]
We want to make it easy to find and try out our new promise-building CLI.
We should create a new page about the CLI, update existing docs that talk about promise building to include the option to use the CLI and how it works, and update our workshops to use it. 
## Tasks
- [x] Write general docs page on how to use the CLI to init a promise from scratch, helm chart and operator
- [x] Update promise building workshop to use CLI
- [ ] Release at least one version of the Kratix CLI
- [x] Install the CLI on the instruqt box
- [ ] Share an announcement in Kratix slack linking to the tool and docs

**Comment by catmo-syntasso** [comment]
Note: Document that null values are assumed to be object

**Comment by ChunyiLyu** [comment]
Document helm values files parsing assumption. Refers to: https://github.com/syntasso/kratix-cli/blob/main/internal/helm_values_schema.go

**Comment by kirederik** [comment]
working branch https://github.com/syntasso/kratix-docs/tree/cli-docs
