### ISSUE TITLE
chore: Update docs.kratix.io to use Termly cookie banner

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#96]
We're now generating our cookie policy via termly, which will automatically update the policy when our cookies change. They provide a consent banner that links to this policy which we should include on our docs site (as well as kratix.io, but I can do that one #Wix4Eva)

You can find the consent banner html snippet in our termly account, login details are in lastpass. Reach out to @catmo-syntasso if you need help finding things

---
### Tasks
- [x] Remove existing cookie policy codeblock
- [x] Add termly consent banner html in the <head> section of website [More how to info here](https://support.termly.io/en/articles/7904618-how-to-install-your-consent-banner)
- [x] Check the new banner appears in the correct format and links to the correct policy

**Comment by richcooper95** [comment]
![Image](https://github.com/user-attachments/assets/b9a8073d-117e-46dd-a889-a91244980b56)

Up and running!

**Comment by kirederik** [comment]
> Termly is up and running on the [kratix.io](http://kratix.io/)  - just realised we need to remove the existing cookie code though, so not > > done yet :large_orange_circle:
> also going to get Stuart's confirmation that the policy all looks good

**Comment by richcooper95** [comment]
Looking at this more deeply, I have a couple of notes:

Our existing code in [Root.js](https://github.com/syntasso/kratix-docs/blob/main/src/theme/Root.js) sets up Google Analytics and Heap, and a cookie-consent banner. Since pushing the change to add the Termly script, the old cookie banner doesn't show up (the new Termly banner does).

On the old banner, if cookies were accepted:
1. Heap is set up.
2. Google Analytics is initialised.

And if cookies are declined:
1. Google Analytics cookies are explicitly removed.

In the new world of Termly, we might need to check via their [API](https://support.termly.io/en/articles/7904658-consent-api-documentation#Step-2:-API-GET-request) whether we can set up GA and Heap in the way we currently do. I also don't see anything about [GA cookies](https://github.com/syntasso/kratix-docs/blob/513e3d831e2d122eb5cf40548c36c4abdae9f4be/src/theme/Root.js#L30) in our Termly dashboard at the moment, so we might need to add them to the list of cookies users can accept.

**Comment by richcooper95** [comment]
We might be able to follow instructions here to set up GA with Termly: https://support.google.com/analytics/answer/14563172?hl=en

**Comment by richcooper95** [comment]
@SaphMB and I have a few questions from our pairing so far:
 
1. Is Wix used to create kratix.io, and Docusaurus for docs.kratix.io? Should we place the cookie banner integration in Wix or Docusaurus? (It's currently Docusaurus, but then we can't control the order of the scripts, which Termly doesn't like.)
4. How does Google Analytics integrate with Termly? Google Consent Mode is likely useful (and is enabled on our Termly at the moment) - but we're not sure how to set up the [Google Tracking ID](https://github.com/syntasso/kratix-docs/blob/513e3d831e2d122eb5cf40548c36c4abdae9f4be/src/theme/Root.js#L6) in that case (there's no reference to it in Termly).
5. Should we keep Heap? If so, how should we handle only initialising it if the cookie policy is accepted? (Is it even cookie-related? Can we just _always_ set up Heap?)
6. What's our Google Analytics login? I don't seem to have access on my Syntasso Gmail (nothing in "All Accounts").

@kirederik - do you know the answer to any of these? Either way, it would be great to chat after lunch if you're free!

**Comment by kirederik** [comment]
>Is Wix used to create kratix.io, and Docusaurus for docs.kratix.io? Should we place the cookie banner integration in Wix or Docusaurus? (It's currently Docusaurus, but then we can't control the order of the scripts, which Termly doesn't like.)

Yes. Kratix.io and Docs.kratix.io are two different websites, each must have their own cookie banner. This story is specific to docs.kratix.io.

>How does Google Analytics integrate with Termly? Google Consent Mode is likely useful (and is enabled on our Termly at the moment) - but we're not sure how to set up the [Google Tracking ID](https://github.com/syntasso/kratix-docs/blob/513e3d831e2d122eb5cf40548c36c4abdae9f4be/src/theme/Root.js#L6) in that case (there's no reference to it in Termly).

I don't know as well. Would need to research.

> Should we keep Heap? If so, how should we handle only initialising it if the cookie policy is accepted? (Is it even cookie-related? Can we just always set up Heap?)

Does Heap use cookies? If so, we can't leave it always enabled. 

>What's our Google Analytics login? I don't seem to have access on my Syntasso Gmail (nothing in "All Accounts").
 added you both

**Comment by SaphMB** [comment]
One consideration when determining whether we need a new website entry for termly is that the termly UI scans for the presence of the consent banner on each website. As the banner is installed on kratix.io, the scans reports that it is installed and there does not appear to be any means of checking whether it is present on anything we have configured as a subdomain (in this case docs.kratix.io)

**Comment by SaphMB** [comment]
@catmo-syntasso We were able to introduce the banner and successfully observe the blocking of cookies in line with _some_ but not all of the previous behaviour. The google analytics cookies were blocked successfully, however, we were unable to block the Heap cookies with Termly. This is currently blocking progress on the story, as a result, we are briefly removing Heap from the scripts that are executed on each page

**Comment by catmo-syntasso** [comment]
Going to reach out to termly about how they integrate wiht other analytics tooling

**Comment by catmo-syntasso** [comment]
Response, haven't inspected in detail yet: 
Hey Paula,
Termly integrates with various third-party vendors for tracking technologies and re marketing services, including Heap Analytics.
To ensure that Termly is properly blocking or allowing cookies from Heap or similar analytics software like Pendo or Amplitude, you may need to configure your Termly settings to recognize these specific cookies and scripts.
Since the integration process can vary based on the analytics software and your website's setup, it's important to refer to the documentation provided by each analytics service for specific integration instructions.
Additionally, Termly's tech stack includes a dedicated API and other tools that could facilitate the integration with analytics platforms. If you encounter issues with integration, these tools may help resolve them.
https://support.termly.io/en/articles/7904658-consent-api-documentation

**Comment by catmo-syntasso** [comment]
The response was wonderfully unhelpful. We have GA working for docs, kratix.io will be fixed soon so we have the analytics everywhere, so i'm moving to done and we'll bin off heap for now.
